[[plugins]]
repo = "thinca/vim-quickrun"
on_ft = ['python']

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = "Yggdroot/indentLine"
on_ft = ['python']

[[plugins]]
repo = "Vimjas/vim-python-pep8-indent"
on_ft = ['python']

[[plugins]]
repo = "zchee/deoplete-jedi"
on_ft = ['python']

[[plugins]]
repo = "lambdalisue/vim-pyenv"
on_ft = ['python']

[[plugins]]
repo = "jmcantrell/vim-virtualenv"
on_ft = ['python']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']
