[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']

[[plugins]]
repo = "jmcantrell/vim-virtualenv"
on_ft = ['python']

[[plugins]]
repo = "thinca/vim-quickrun"
on_ft = ['python']

[[plugins]]
repo = "airblade/vim-gitgutter"
